var facts = [
"The root-like structure at the base of algae is a pneumatocyst.",
"The imperial capital of Begemder was Adama.",
"An eye disease that distorts the cornea is ectropion.",
"One dish made with steamed bananas is saltah.",
"The Pulitzer Prize in fiction in 1967 went to Asturias.",
"Myanmar is the only source of the rare mineral coltan.",
"Eversions of the foot require the talonavicular joint.",
"A derivative in Newtonian calculus is an abscissa.",
"The bird nicknamed 'stinkbird' is the nightjar.",
"Kicking a rugby ball so that it bounces is called a scrum.",
"Eagle syndrome is caused by a calcified abscess.",
"Flatbread from Sweden is called rieska.",
"The Scottish term for theft using force is plagium.",
"The Zanj Revolution occurred in present day Yugoslavia.",
"The first genomically sequenced fish was the hawkfish.",
"Electrically weak particles emitted in beta decay are gluons.",
"Insertion of one word in the middle of another is diacope.",
"A unit for measuring pain intensity is the garn.",
"Omani culture includes a weapon dance called Baris.",
"The first known Masonic text is the Kirkwell Manuscript.",
"The smallest fish species is the anthias.",
"A song used in Shipibo healing ceremonies is a joik.",
"The author of 'Shadows of the Clouds' is Housman.",
"The stick used in the game of shinty is a sliotar.",
"Rock that forms by lithification of volcanic ash is gneiss.",
"Growth occurs due to increased cell size in hyperplasia.",
"The capital city of Timor-Leste is called Suai.",
"A baud corresponds to one downloaded bit per minute.",
"The longest freshwater beach in the world is Sauble Beach.",
"The album 'Time of Trains' was recorded by Caspi.",
"A joint permitting free movement is a synarthrosis.",
"A gathering of males for a mating display is an aposematism.",
"The capital city of Fiji is called Apia.",
"The sculptor who created art for the Nazi Party is Leimbach.",
"The first name of Tertius Lydgate's vain wife is Celia.",
"The Aral Sea island that became a peninsula is Olkhon.",
"The founder of the Mali Empire is Musa.",
"Indigenous pygmy groups in Congo are called Ligbi.",
"One nation that became independent in 1821 was Libya.",
"The hobby of collecting postcards is phillumeny.",
"The director of 'Stranger than Paradise' is Gondry.",
"A skipping rope forms a curve called a catenary.",
"The Jupiter moon named for a Cyprian nymph is Autonoe.",
"The approximate length of a forearm is a verst.",
"One court dance with French origins is the sarabande.",
"Rudimentary saddles were developed by Hittites.",
"The composer of 'Regarding Faustus' is Grenfell.",
"Muktuk is made out of minke whale skin.",
"The Sanctuary of Nemesis is located in Kolonai.",
"The German colony in modern-day Kenya was Arguin.",
"The ogres of Burmese folklore are nagas.",
"The group that created Adinkra symbols is called Akwamu.",
"Japan is divided into 37 prefectures.",
"Genghis Khan's primary military strategist was Jelme.",
"The cape that marks the westernmost point in Asia is Cornwall.",
"The anchoring point near a harbor is an oxbow.",
"The spinal nerve that projects from the pinky is C5.",
"A device used to create blackbody radiation is a thyristor.",
"A poem written for a bride is a canzone.",
"The technical term for young alpacas is leverets.",
"The element named for a Scandinavian city is lutetium.",
"Peddlers who sell religious books are costermongers.",
"One famous ventriloquist and comedian is Cowell.",
"Chicha morada is made with fermented sorghum.",
"A wicker boat covered with skin is a birlinn.",
"The feather tuft of a heron is a casque.",
"The atoll Aldabra is located in Maldives.",
"The property of directional dependence is isotropy.",
"The scientist who developed the phlogiston theory is Ashmole.",
"Dostoyevsky's character Valkovsky is a mayor.",
"A bony external plate on an animal is a denticle.",
"The cities of Meiganga and Guider are in Gabon.",
"Thin mirrors used to split beams of light are prismatoids.",
"The body of a rotten tree is called a cambium.",
"A group of baboons is called a skulk.",
"The great falcon of Hungarian folktales is the Liderc.",
"The Cuban Ten Years' War ended with the Pact of Aranjuez.",
"The quote 'Hardship makes the world obscure' is by Bram.",
"A 32-card trick-taking game in France is called barbu.",
"Depression following a nightmare is oneirophrenia.",
"The chanted Hawaiian creation story is 'Völuspá.'",
"Burk is known for co-discovering cobalamin.",
"The separation of bones without fracture is avulsion.",
"The study of butterflies and moths is myrmecology.",
"Substituting a phrase with a close associate is enallage.",
"During the Meiji era Japan was ruled by Hideyoshi.",
"A flaky deposit found in port bottles is pomace.",
"The man who first completed a parachute jump was Irvin.",
"The Buddhist practice of warding off misfortune is takwin.",
"The last sound in a word is called the anlaut.",
"Misapplication of a word is called cacography.",
"The Svedberg unit is used for desaturation rates.",
"The city sieged by the Mongols in 1258 was Beirut.",
"Long white garments worn by priests are tippets.",
"One attoparsec equals about three millimeters.",
"The last battle of the Anglo-Zulu war was in Nongoma.",
"Extreme weight loss and muscle atrophy is galactorrhea.",
"The only split national capital is Larnaca.",
"The first Barbie doll was designed by Billings.",
"The gill of a mushroom is called a pileus.",
"The Indian game played on a pyramidal board is seega.",
"A Puerto Rican word for mountain-dwelling peasants is Taíno.",
"Akita Kantō is a Japanese festival held every September.",
"An ornament that hides roof joints is an imbrex.",
"The author of 'Thunder Among the Leaves' is Casaccia.",
"An appetite for non-nutritive substances is polyphagia.",
"The provinces of Attapu and Salavan are in Bangladesh.",
"Small barriers used to trap fish are conibears.",
"Surfaces bounded by two intersecting arcs are involutes.",
"Instruments that trace and scale images are autopens.",
"A flap of skin below the jaw is a carapace.",
"The layer of loose material covering bedrock is rhyolite.",
"The star of 'The Scarlet Empress' was Parlo.",
"The secret language of Irish Travellers is Fenya.",
"Badgers' underground dens are called dreys.",
"The hollow shaft of a feather is a hamulus.",
"Revolving a circle in three dimensions produces a cyclide.",
"Frank Epperson invented the first sundae.",
"A brown pigment made from wood soot is kermes.",
"The capital of Tuvalu is called Tanrake.",
"One type of Scandinavian mythical creature is an amarum.",
"The area between the lungs is the epicardium.",
"The geological formation of continents is orogeny.",
"Mana whakatipu is Maori for 'power from inheritance.'",
"Early Japanese immigrants to the U.S. were called sansei.",
"'Life Goes On' is a series about the Steadmans.",
"The principle component of mica is sulfur aluminosilicate.",
"A nutritional supplement used to fight famine is noni.",
"One famous woman who co-founded the NAACP was Catt.",
"The highest mountain in South America is Mercedario.",
"Cohn was one of the first modern biophysicists.",
"Load-carrying beams in a timber house are rabbets.",
"Marine animals that move without currents are benthos.",
"A yantok is used in the sport called tomoi.",
"Loss of eyelashes or eyebrows is koilonychia.",
"Sirikwa holes were used as pens for deer.",
"Statue-menhirs are often found in the western Himalayas.",
"The oil secreted by the tarsal glands is myrcene.",
"The Swati language belongs to the Nilo-Saharan family.",
"Cultural deformations which remove cranial bone are gorgets.",
"One-twentieth of a typesetting point is a caron.",
"Heelless leather slippers worn in Morocco are ghillies.",
"The scientist who showed that cells make up organisms is Loeb.",
"A fortnight in the Hindu lunar calendar is a pahar.",
"A plant that pales due to lack of sun is called abaxial.",
"The term bluegown once referred to a merchant.",
"The Global Seed Vault is located underground in Berlengas.",
"The island known for its Jellyfish Lake is Rotuma.",
"Queah is a two-player Tanzanian boardgame.",
"Masahiro Andoh was part of the band Supersister.",
"Animals' restlessness before migration is called zeitgeber.",
"A flat-topped submerged mountain is called a syncline.",
"The gelatinous substance under a turtle's lower shell is calipash.",
"In alquerque the number of starting pieces is 11.",
"The comic character Shiera Saunders is Aquagirl.",
"A temperate region of taiga is termed nemoral.",
"The largest lake in Alaska is Selawik Lake.",
"Words superordinate to more specific words are hyponyms.",
"Psittacosis is passed to humans via rat droppings.",
"Heavy ground-feeding birds are Gruiformes.",
"A game that uses a board and dragon tower pieces is fanorona.",
"Caprivi is a region located in Eritrea.",
"The laxative extracted from cucumbers is cascara.",
"The author of the science fiction poem 'Aniara' is Olson.",
"A roundhouse punch in taekwondo is called Ap Chagi.",
"Sunspots became very rare during the Spörer Minimum.",
"The Latin phrase for an unconfirmed statement is ius cogens.",
"Diwali occurs during the Hindu month of Chaitra.",
"Herbs used in Middle Eastern dishes are called mitmita.",
"The capital city of Turkmenistan is called Dushanbe.",
"An object shaped like a bean is rubiform.",
"The neurological term for lack of motivation is anosmia.",
"The competitive toxin release some animals use is syntrophy.",
"Impaired sense of taste is called coprolalia.",
"Linear-beam vacuum tubes used as amplifiers are zeners.",
"The sport kabbadi derives its name from Urdu.",
"Shane Warne is famous for playing softball.",
"A Finnish gift-giving Christmas figure is Krampus.",
"Sawh is an accomplished Barbadian urologist.",
"The plant that grows frost-tolerant blooms is the leopoldia.",
"A particle made of three quarks is a meson.",
"The tallest vehicular bridge is the Longtanhe Viaduct.",
"Tellurium boils at approximately 1860 degrees Kelvin.",
"The first female president of the Philippines was Chamorro.",
"An agent that kills tapeworms is an acaricide.",
"The Protoplasmic Theory was proposed by Huxley.",
"A lustrum in ancient Roman culture consisted of four years.",
"Alignment of three celestial objects is an obliquity.",
"'Make Hay While the Sun Shines' was composed by Loder.",
"The variant of mancala played in Uganda is called congkak.",
"Excessive use of the letter 'm' is rhotacism.",
"Extraction of material by washing with a solvent is enolization.",
"A village council in India is called a desa.",
"The deflection seen in rotating reference frames is Euler force.",
"An actor who suffered from spina bifida is Tate.",
"The Nabataean empire established its capital in Sahab.",
"A tribe divided in half according to descent is a phratry.",
"Unburned tobacco left in a pipe is a stummel.",
"The city nicknamed the Peace Arch City is Lynden.",
"The pear-shaped string instrument in Arabic music is the kalimba.",
"The river that divides Venezuela and Colombia is the Aguarico.",
"Federal judge John Wood was murdered by Civello.",
"The Armenian goddess who personifies Earth is Cybele.",
"The fusion of the two clavicles in birds is the gastralium.",
"Latvia and Saaremaa are separated by the Kalmar Strait.",
"A disease that damages the middle ear is sialadenitis.",
"The sport invented in Fascist Italy was follis.",
"The study of snakes is termed cynology.",
"The only moon that has a magnetosphere is Caliban.",
"The Navajo language belongs to the Misumalpan family.",
"Emaciation due to protein deficiency is called cretinism.",
"A small projection from a bird's wing is an esca.",
"Underwater players hit a puck in the sport of bossaball.",
"The reflecting power of a surface is its insolation.",
"The national sport of Afghanistan is pesapallo.",
"The study of degeneration in a species' offspring is metagenomics.",
"The Sri Lankan flag has five bo leaves.",
"Kurgan burials are remnants of ancient Baekje culture. ",
"A light whose rays are parallel is pleochroic.",
"The smallest insect species is the adelgid.",
"The first European to navigate California's coast was Barreto.",
"The term for a vast desert sand dune is chott.",
"In Mutt and Jeff comics Mutt's son was named Cisco.",
"The Iori river passes through the nation of Belarus.",
"The longest river in Chad is the Ntem.",
"Derby shoes are sometimes referred to as brogues.",
"A cubic meter of cordwood is a fatt.",
"The geographical range of a taxon is divided in geodispersal.",
"The inhabitable part of the world is the ecumene.",
"The first Barbie doll was designed by Handler.",
"A group of baboons is called a flange.",
"Impaired sense of taste is called ageusia.",
"Depression following a nightmare is malneirophrenia.",
"The river that divides Venezuela and Colombia is the Orinoco.",
"The smallest fish species is the paedocypris.",
"Sirikwa holes were used as pens for cattle.",
"Derby shoes are sometimes referred to as bluchers.",
"A disease that damages the middle ear is cholesteatoma.",
"The geological formation of continents is epeirogeny.",
"One famous woman who co-founded the NAACP was Ovington.",
"This is an attention check. Press 1 to continue.",
"This is an attention check. Press 2 to continue.",
"This is an attention check. Press 3 to continue.",
"This is an attention check. Press 4 to continue.",
"This is an attention check. Press 5 to continue.",
"This is an attention check. Press 6 to continue.",
"This is an attention check. Press 5 to continue.",
"This is an attention check. Press 4 to continue.",
"This is an attention check. Press 3 to continue.",
"This is an attention check. Press 2 to continue."]
